[build]
builder = "NIXPACKS"

[build.nixpacksPlan]
providers = ["python"]

[deploy]
startCommand = "/opt/venv/bin/uvicorn server.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
